# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aksesuarlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adi', models.CharField(help_text='\xdcr\xfcnle beraber getirilen t\xfcm aksesuarlar. \xd6rn: Batarya, \xc7anta', max_length=30, verbose_name='Adi')),
            ],
            options={
                'verbose_name': 'Aksesuar',
                'verbose_name_plural': 'Aksesuarlar',
            },
        ),
        migrations.CreateModel(
            name='Durumlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Durumu', models.CharField(help_text='Metin alan\u0131n\u0131n alt\u0131nda kay\u0131t girerken yard\u0131mc\u0131 olabilecek konular\u0131 anlatan k\u0131sa bir a\xe7\u0131klama yazabilirsiniz.', max_length=30, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Durum',
                'verbose_name_plural': 'Durumlar',
            },
        ),
        migrations.CreateModel(
            name='Musteriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aktif', models.BooleanField(default=1)),
                ('Kodu', models.CharField(default='21755294', max_length=8, verbose_name='M\xfc\u015fteri Kodu')),
                ('Unvan', models.CharField(max_length=250, verbose_name='Ticari \xdcnvan')),
                ('Yetkili', models.CharField(max_length=250, verbose_name='Yetkili Ad\u0131 Soyad\u0131')),
                ('Telefon', models.CharField(blank=True, max_length=13, verbose_name='Telefon')),
                ('KayitTarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Kay\u0131t Tarihi')),
            ],
            options={
                'verbose_name': 'M\xfc\u015fteri',
                'verbose_name_plural': 'M\xfc\u015fteriler',
            },
        ),
        migrations.CreateModel(
            name='ServisForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeslimEden', models.CharField(max_length=130, verbose_name='Teslim Eden')),
                ('FormNo', models.CharField(default='22608778', max_length=8, verbose_name='Form No')),
                ('KayitTarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kay\u0131t Tarihi')),
                ('Musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisformu.Musteriler')),
            ],
            options={
                'verbose_name': 'Servis Formu',
                'verbose_name_plural': 'Formlar',
            },
        ),
        migrations.CreateModel(
            name='Teknisyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aktif', models.BooleanField(default=1)),
                ('AdSoyad', models.CharField(max_length=250, verbose_name='Ad\u0131 Soyad\u0131')),
                ('KayitTarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Kay\u0131t Tarihi')),
            ],
            options={
                'verbose_name': 'Teknisyen',
                'verbose_name_plural': 'Teknisyenler',
            },
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cins', models.CharField(max_length=30, verbose_name='Cinsi')),
                ('Marka', models.CharField(max_length=50, verbose_name='Marka')),
                ('Model', models.CharField(max_length=50, verbose_name='Model')),
                ('SeriNo', models.CharField(max_length=250, verbose_name='Seri No')),
                ('GarantiBitis', models.DateField(default=django.utils.timezone.now, verbose_name='Garanti Biti\u015f')),
                ('Sikayet', models.TextField(verbose_name='\u015eikayet')),
                ('Not', models.TextField(blank=True, verbose_name='Yap\u0131lan \u0130\u015flemler')),
                ('Aksesuar', models.ManyToManyField(blank=True, to='servisformu.Aksesuarlar')),
                ('Durum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisformu.Durumlar')),
                ('ServisFormu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisformu.ServisForm')),
            ],
            options={
                'verbose_name': '\xdcr\xfcn',
                'verbose_name_plural': '\xdcr\xfcnler',
            },
        ),
        migrations.AddField(
            model_name='servisform',
            name='TeslimAlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servisformu.Teknisyen'),
        ),
    ]
