# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servisformu', '0004_auto_20160114_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='TeslimatTarihi',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Teslimat Tarihi'),
        ),
        migrations.AlterField(
            model_name='musteriler',
            name='Kodu',
            field=models.CharField(default='98930143', max_length=8, verbose_name='M\xfc\u015fteri Kodu'),
        ),
        migrations.AlterField(
            model_name='servisform',
            name='FormNo',
            field=models.CharField(default='21352374', max_length=8, verbose_name='Form No'),
        ),
    ]
